# Generated by Django 6.0.2 on 2026-02-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='daily_energy_limit_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='power_limit_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='relay_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='schedule_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='schedule_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='schedule_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
