# Generated by Django 6.0 on 2026-01-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cloud_cover', models.IntegerField()),
                ('sunrise', models.DateTimeField()),
                ('sunset', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
