# Generated by Django 6.0.2 on 2026-02-26 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetryreading',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
